modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="strykerzmods"
version="1.0.0"
displayName="strykerzMods"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Megaport, MCreator"

[[dependencies.strykerzmods]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




