modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="strykerzmods"
version="1.0.0"
displayName="strykerzMods"
credits="Mon GitHub: https://github.com/strykerzOfficiel"
displayURL="https://github.com/strykerzOfficiel"
logoFile="logo.png"
authors="StrykerzOfficiel"
description='''
Mod pour la survie ou pour les serveur
'''

[[dependencies.strykerzmods]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




